FROM golang:1.15-alpine

RUN apk update && apk upgrade && \
  apk add --no-cache bash git openssh

WORKDIR /app

COPY . .


RUN go mod download


RUN go build -o runserver cmd/main.go 

EXPOSE 5000

CMD ["./runserver"]